[package]
authors.workspace = true
description.workspace = true
edition.workspace = true
license.workspace = true
name = "qp-wormhole-verifier"
version.workspace = true

[dependencies]
anyhow = { workspace = true }
qp-plonky2-verifier = { version = "1.1.5", default-features = false }
qp-wormhole-inputs = { path = "../inputs", default-features = false }

[dev-dependencies]
criterion = { workspace = true }
qp-plonky2-field = { version = "1.1.3", features = ["rand"] }
qp-wormhole-prover = { path = "../prover" }

[features]
default = ["std"]
std = [
	"anyhow/std",
	"qp-plonky2-verifier/std",
	"qp-wormhole-inputs/std",
]

[lints]
workspace = true

[[bench]]
harness = false
name = "verifier"
