[package]
authors.workspace = true
description.workspace = true
edition.workspace = true
license.workspace = true
name = "qp-zk-circuits-common"
version.workspace = true

[dependencies]
anyhow = { workspace = true, default-features = false }
hex = { workspace = true }
qp-plonky2 = { workspace = true, default-features = false, features = ["no_random"] }
qp-poseidon-core = { workspace = true, default-features = false, features = [
	"p2",
	"p3",
] }
serde = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }
rand = "0.8"

[[bench]]
name = "merkle_tree"
harness = false

[features]
default = ["std"]
no_random = ["qp-plonky2/no_random"]
std = ["anyhow/std", "qp-plonky2/std", "qp-poseidon-core/std", "serde/std"]
