[package]
name = "qp-wormhole-inputs"
description = "Public input types for Wormhole circuit proofs"
authors.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
anyhow = { workspace = true, default-features = false }
log = { version = "0.4", default-features = false }

[features]
default = ["std"]
std = ["anyhow/std", "log/std"]

[lints]
workspace = true
